"""
System Evaluation Script.
Runs DeptAI's actual pipeline against a hand-labeled test set and measures:
  1. Domain-restriction accuracy (precision / recall / F1 / confusion matrix)
  2. Retrieval latency (embed + hybrid search) over indexed documents
  3. Response validation confidence on live query logs
  4. Document indexing success rate
  5. Cache hit rate

This produces REAL numbers from the code (not placeholders). Run it after you've
seeded the database, uploaded documents, and made some test queries through the app:

    python scripts/evaluate_system.py

Results are printed to the console and saved to data/eval_results.json, which the
admin dashboard's Performance endpoint (/api/admin/performance) will pick up and
display automatically.
"""

import sys
import os
import json
import time
import asyncio
from datetime import datetime

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from app.core.database import SessionLocal
from app.services.domain_checker import domain_checker
from app.services.cache_service import cache_service
from app.rag.pipeline import rag_pipeline
from app.models.document import Document
from app.models.query_log import QueryLog


# ══════════════════════════════════════════════════════════════
# HAND-LABELED TEST SET
# Ground truth was assigned by the project team, not generated by the model.
# ══════════════════════════════════════════════════════════════
IN_DOMAIN_QUERIES = [
    "What is the minimum CGPA required to graduate?",
    "How do I submit my thesis?",
    "When is the course registration deadline?",
    "What is the attendance policy for this semester?",
    "How can I apply for a course waiver?",
    "Who is my faculty advisor?",
    "What are the steps to get an official transcript?",
    "When are tuition fees due?",
    "Can I take an elective from another department?",
    "What is the procedure for a scholarship renewal?",
    "How do I contact my thesis supervisor?",
    "What documents are needed for the internship application?",
    "Is there a form for changing my major?",
    "What is the credit requirement for this semester?",
    "When does the add/drop period end?",
    "How do I check my exam results?",
    "What is the department's grading policy?",
    "Where can I find the class timetable?",
    "How do I request a leave of absence?",
    "What are the lab requirements for this course?",
]

OUT_OF_DOMAIN_QUERIES = [
    "What's the weather like today?",
    "Can you recommend a good recipe for biryani?",
    "Who won the cricket match yesterday?",
    "What's a good movie to watch this weekend?",
    "Should I invest in Bitcoin?",
    "Tell me a funny joke.",
    "My girlfriend and I are having relationship issues, any advice?",
    "Who do you think will win the next election?",
    "Can you translate this sentence into French?",
    "Write me a poem about the ocean.",
    "What is the capital of France?",
    "Explain how black holes form.",
    "What's 2 + 2?",
    "Tell me about the history of ancient Rome.",
    "What's the best smartphone to buy right now?",
]


async def evaluate_domain_checker():
    """Run the labeled test set through domain_checker.check() and score it."""
    tp = fp = tn = fn = 0
    per_query = []

    for q in IN_DOMAIN_QUERIES:
        result = await domain_checker.check(q)
        correct = result.is_in_domain is True
        if correct:
            tp += 1
        else:
            fn += 1
        per_query.append({"query": q, "expected": True, "predicted": result.is_in_domain,
                           "confidence": result.confidence_score, "method": result.method})

    for q in OUT_OF_DOMAIN_QUERIES:
        result = await domain_checker.check(q)
        correct = result.is_in_domain is False
        if correct:
            tn += 1
        else:
            fp += 1
        per_query.append({"query": q, "expected": False, "predicted": result.is_in_domain,
                           "confidence": result.confidence_score, "method": result.method})

    total = tp + fp + tn + fn
    precision = tp / (tp + fp) if (tp + fp) else 0.0
    recall = tp / (tp + fn) if (tp + fn) else 0.0
    f1 = 2 * precision * recall / (precision + recall) if (precision + recall) else 0.0
    accuracy = (tp + tn) / total if total else 0.0
    # FPR: out-of-domain queries wrongly accepted, as a fraction of all actual out-of-domain queries
    fpr = fp / (fp + tn) if (fp + tn) else 0.0
    # FNR: in-domain queries wrongly rejected, as a fraction of all actual in-domain queries
    fnr = fn / (fn + tp) if (fn + tp) else 0.0

    return {
        "test_set_size": total,
        "in_domain_count": len(IN_DOMAIN_QUERIES),
        "out_of_domain_count": len(OUT_OF_DOMAIN_QUERIES),
        "confusion_matrix": {"true_positive": tp, "false_positive": fp, "true_negative": tn, "false_negative": fn},
        "accuracy": round(accuracy * 100, 1),
        "precision": round(precision * 100, 1),
        "recall": round(recall * 100, 1),
        "f1_score": round(f1, 3),
        "false_positive_rate": round(fpr * 100, 1),
        "false_negative_rate": round(fnr * 100, 1),
        "per_query": per_query,
    }


async def evaluate_retrieval_latency(db):
    """Time embed + hybrid-search retrieval over currently indexed documents,
    broken down by pipeline stage (embed / hybrid search / rerank)."""
    from app.rag.embedder import embedding_service
    from app.rag.vector_store import vector_store
    from app.rag.reranker import reranker
    import time as _time

    await rag_pipeline.initialize(db)

    if not rag_pipeline.is_ready:
        return {"ready": False, "note": "No documents indexed yet — upload and index documents, then re-run."}

    sample_queries = IN_DOMAIN_QUERIES[:10]
    embed_ms, search_ms, rerank_ms, total_ms = [], [], [], []
    result_counts = []

    for q in sample_queries:
        t0 = _time.perf_counter()
        query_embedding = embedding_service.embed_query(q)
        t1 = _time.perf_counter()
        results = vector_store.hybrid_search(query_embedding=query_embedding, query_text=q, top_k=5, alpha=0.6)
        t2 = _time.perf_counter()
        if reranker.is_available and results:
            chunks_scores = [(f"[Source: {c.source}]\n{c.text}", s) for c, s in results]
            reranker.rerank(q, chunks_scores, top_k=5)
        t3 = _time.perf_counter()

        embed_ms.append((t1 - t0) * 1000)
        search_ms.append((t2 - t1) * 1000)
        rerank_ms.append((t3 - t2) * 1000)
        total_ms.append((t3 - t0) * 1000)
        result_counts.append(len(results))

    def _stats(vals):
        vals = sorted(vals)
        n = len(vals)
        return {
            "avg_ms": round(sum(vals) / n, 1),
            "p50_ms": round(vals[n // 2], 1),
            "p95_ms": round(vals[min(n - 1, int(n * 0.95))], 1),
            "min_ms": round(vals[0], 1),
            "max_ms": round(vals[-1], 1),
        }

    n = len(sample_queries)
    return {
        "ready": True,
        "queries_tested": n,
        "avg_chunks_returned": round(sum(result_counts) / n, 1),
        "stage_breakdown": {
            "embed": _stats(embed_ms),
            "hybrid_search": _stats(search_ms),
            "rerank": _stats(rerank_ms) if reranker.is_available else None,
        },
        # Kept flat for convenience/back-compat with the admin dashboard.
        "avg_retrieval_ms": round(sum(total_ms) / n, 1),
        "p50_retrieval_ms": round(sorted(total_ms)[n // 2], 1),
        "p95_retrieval_ms": round(sorted(total_ms)[min(n - 1, int(n * 0.95))], 1),
        "min_retrieval_ms": round(min(total_ms), 1),
        "max_retrieval_ms": round(max(total_ms), 1),
    }


RETRIEVAL_TEST_SET_PATH = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "data", "retrieval_test_set.json"
)


async def evaluate_retrieval_quality(db):
    """
    Recall@5, Precision@5, MRR — requires ground truth (which document a query
    should retrieve from). This is genuinely un-measurable without labeled data,
    so it reads data/retrieval_test_set.json:

        [{"query": "...", "expected_source": "student-handbook.pdf"}, ...]

    expected_source must match the filename of a document you've uploaded and
    indexed. Skips gracefully with instructions if the file doesn't exist yet.
    """
    if not os.path.exists(RETRIEVAL_TEST_SET_PATH):
        return {
            "ready": False,
            "note": (
                "No labeled retrieval test set found. Create "
                "data/retrieval_test_set.json as a list of "
                '{"query": "...", "expected_source": "<uploaded filename>"} '
                "pairs using your real indexed documents, then re-run."
            ),
        }

    with open(RETRIEVAL_TEST_SET_PATH) as f:
        test_set = json.load(f)

    if not rag_pipeline.is_ready:
        await rag_pipeline.initialize(db)
    if not rag_pipeline.is_ready:
        return {"ready": False, "note": "Test set found, but no documents are indexed yet."}

    recall_hits, precision_scores, reciprocal_ranks = [], [], []
    per_query = []

    for item in test_set:
        q, expected = item["query"], item["expected_source"]
        result = await rag_pipeline.retrieve(q, top_k=5, use_hybrid=True)
        sources_in_order = [s for chunk in result.chunks for s in [chunk.split("]\n", 1)[0].replace("[Source: ", "")]]

        hit = expected in sources_in_order
        recall_hits.append(1 if hit else 0)
        precision_scores.append(sources_in_order.count(expected) / len(sources_in_order) if sources_in_order else 0)
        rank = next((i + 1 for i, s in enumerate(sources_in_order) if s == expected), None)
        reciprocal_ranks.append(1 / rank if rank else 0)
        per_query.append({"query": q, "expected_source": expected, "hit_at_5": hit, "rank": rank})

    n = len(test_set)
    return {
        "ready": True,
        "test_set_size": n,
        "recall_at_5": round(sum(recall_hits) / n * 100, 1),
        "precision_at_5": round(sum(precision_scores) / n * 100, 1),
        "mrr": round(sum(reciprocal_ranks) / n, 3),
        "per_query": per_query,
    }


async def evaluate_retrieval_baseline_comparison(db):
    """
    Compare semantic-only (FAISS) vs keyword-only (BM25) vs hybrid retrieval —
    timing always, plus Recall@5/Precision@5/MRR if the labeled test set exists.
    """
    from app.rag.embedder import embedding_service
    from app.rag.vector_store import vector_store
    from app.rag.bm25_search import bm25_searcher
    import time as _time

    if not rag_pipeline.is_ready:
        await rag_pipeline.initialize(db)
    if not rag_pipeline.is_ready:
        return {"ready": False, "note": "No documents indexed yet."}

    has_labels = os.path.exists(RETRIEVAL_TEST_SET_PATH)
    test_set = json.load(open(RETRIEVAL_TEST_SET_PATH)) if has_labels else [{"query": q} for q in IN_DOMAIN_QUERIES[:10]]

    methods = {"semantic_only": [], "keyword_only": [], "hybrid": []}
    hits = {"semantic_only": [], "keyword_only": [], "hybrid": []}
    ranks = {"semantic_only": [], "keyword_only": [], "hybrid": []}

    for item in test_set:
        q = item["query"]
        expected = item.get("expected_source")
        query_embedding = embedding_service.embed_query(q)

        t0 = _time.perf_counter()
        semantic_results = vector_store.search(query_embedding, top_k=5)
        t1 = _time.perf_counter()
        keyword_results = bm25_searcher.search(q, top_k=5)
        t2 = _time.perf_counter()
        hybrid_results = vector_store.hybrid_search(query_embedding=query_embedding, query_text=q, top_k=5, alpha=0.6)
        t3 = _time.perf_counter()

        methods["semantic_only"].append((t1 - t0) * 1000)
        methods["keyword_only"].append((t2 - t1) * 1000)
        methods["hybrid"].append((t3 - t2) * 1000)

        if expected:
            sem_sources = [c.source for c, _ in semantic_results]
            kw_sources = [meta["source"] for _, _, meta in keyword_results] if keyword_results else []
            hyb_sources = [c.source for c, _ in hybrid_results]
            for name, srcs in [("semantic_only", sem_sources), ("keyword_only", kw_sources), ("hybrid", hyb_sources)]:
                hits[name].append(1 if expected in srcs else 0)
                rank = next((i + 1 for i, s in enumerate(srcs) if s == expected), None)
                ranks[name].append(1 / rank if rank else 0)

    n = len(test_set)
    result = {"ready": True, "queries_tested": n, "has_labeled_accuracy": has_labels, "methods": {}}
    for name in methods:
        entry = {"avg_latency_ms": round(sum(methods[name]) / n, 1)}
        if has_labels and hits[name]:
            entry["recall_at_5"] = round(sum(hits[name]) / n * 100, 1)
            entry["mrr"] = round(sum(ranks[name]) / n, 3)
        result["methods"][name] = entry
    return result


def evaluate_document_indexing(db):
    """Extraction/indexing success rate from actual Document rows."""
    docs = db.query(Document).all()
    total = len(docs)
    if total == 0:
        return {"total_uploaded": 0, "note": "No documents uploaded yet."}

    indexed = sum(1 for d in docs if d.status == "indexed")
    failed = sum(1 for d in docs if d.status == "failed")
    processing = sum(1 for d in docs if d.status in ("uploaded", "processing"))
    total_chunks = sum(d.chunk_count or 0 for d in docs)

    return {
        "total_uploaded": total,
        "indexed": indexed,
        "failed": failed,
        "processing_or_pending": processing,
        "extraction_success_rate": round(indexed / total * 100, 1),
        "total_chunks_indexed": total_chunks,
    }


def evaluate_from_query_logs(db):
    """Aggregate real numbers already logged from live app usage (QueryLog table)."""
    logs = db.query(QueryLog).all()
    total = len(logs)
    if total == 0:
        return {"total_logged_queries": 0, "note": "No chat queries logged yet — use the chat interface first."}

    resolved = sum(1 for l in logs if l.status == "resolved")
    rejected = sum(1 for l in logs if l.is_in_domain is False)
    response_times = [l.response_time_ms for l in logs if l.response_time_ms is not None]
    confidences = [l.confidence_score for l in logs if l.confidence_score is not None]

    method_counts = {}
    for l in logs:
        m = l.retrieval_method or "unknown"
        method_counts[m] = method_counts.get(m, 0) + 1

    result = {
        "total_logged_queries": total,
        "resolved": resolved,
        "resolution_rate": round(resolved / total * 100, 1),
        "domain_rejection_rate": round(rejected / total * 100, 1),
        "retrieval_method_breakdown": method_counts,
    }
    if response_times:
        response_times.sort()
        n = len(response_times)
        result["response_time_ms"] = {
            "avg": round(sum(response_times) / n, 1),
            "p50": response_times[n // 2],
            "p95": response_times[min(n - 1, int(n * 0.95))],
            "min": response_times[0],
            "max": response_times[-1],
        }
    if confidences:
        result["avg_response_confidence"] = round(sum(confidences) / len(confidences), 3)
        result["low_confidence_responses"] = sum(1 for c in confidences if c < 0.5)

    return result


async def main():
    print("=" * 70)
    print("DeptAI — System Performance Evaluation")
    print(f"Run at: {datetime.utcnow().isoformat()}Z")
    print("=" * 70)

    db = SessionLocal()
    try:
        print("\n[1/6] Domain restriction accuracy (labeled test set)...")
        domain_results = await evaluate_domain_checker()
        print(f"  Accuracy: {domain_results['accuracy']}% | Precision: {domain_results['precision']}% | "
              f"Recall: {domain_results['recall']}% | F1: {domain_results['f1_score']}")
        print(f"  FPR: {domain_results['false_positive_rate']}% | FNR: {domain_results['false_negative_rate']}%")
        print(f"  Confusion matrix: {domain_results['confusion_matrix']}")

        print("\n[2/6] Retrieval latency (stage breakdown: embed / hybrid search / rerank)...")
        retrieval_results = await evaluate_retrieval_latency(db)
        if retrieval_results.get("ready"):
            print(f"  Avg total: {retrieval_results['avg_retrieval_ms']}ms | "
                  f"p95: {retrieval_results['p95_retrieval_ms']}ms | "
                  f"tested on {retrieval_results['queries_tested']} queries")
        else:
            print(f"  Skipped: {retrieval_results.get('note')}")

        print("\n[3/6] Retrieval quality (Recall@5 / Precision@5 / MRR)...")
        quality_results = await evaluate_retrieval_quality(db)
        if quality_results.get("ready"):
            print(f"  Recall@5: {quality_results['recall_at_5']}% | "
                  f"Precision@5: {quality_results['precision_at_5']}% | MRR: {quality_results['mrr']}")
        else:
            print(f"  Skipped: {quality_results.get('note')}")

        print("\n[4/6] Baseline comparison (semantic-only vs keyword-only vs hybrid)...")
        baseline_results = await evaluate_retrieval_baseline_comparison(db)
        if baseline_results.get("ready"):
            for name, m in baseline_results["methods"].items():
                extra = f" | Recall@5: {m['recall_at_5']}% | MRR: {m['mrr']}" if "recall_at_5" in m else ""
                print(f"  {name}: {m['avg_latency_ms']}ms{extra}")
        else:
            print(f"  Skipped: {baseline_results.get('note')}")

        print("\n[5/6] Document indexing success rate...")
        doc_results = evaluate_document_indexing(db)
        print(f"  {doc_results}")

        print("\n[6/6] Live query log aggregates + cache hit rate...")
        log_results = evaluate_from_query_logs(db)
        print(f"  {log_results}")
        cache_results = cache_service.get_stats()
        print(f"  Cache: {cache_results}")

        output = {
            "generated_at": datetime.utcnow().isoformat() + "Z",
            "domain_restriction": domain_results,
            "retrieval_latency": retrieval_results,
            "retrieval_quality": quality_results,
            "retrieval_baseline_comparison": baseline_results,
            "document_indexing": doc_results,
            "query_logs": log_results,
            "cache": cache_results,
        }

        out_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "data")
        os.makedirs(out_dir, exist_ok=True)
        out_path = os.path.join(out_dir, "eval_results.json")
        with open(out_path, "w") as f:
            json.dump(output, f, indent=2)

        print(f"\nSaved full results to {out_path}")
        print("These numbers will now also appear under Admin → Performance in the app.")

    finally:
        db.close()


if __name__ == "__main__":
    asyncio.run(main())
